name: iranian_banks
description: A Flutter package to detect Iranian banks from card or IBAN numbers.
version: 0.0.1
homepage: https://github.com/yourusername/iranian_banks
repository: https://github.com/yourusername/iranian_banks
issue_tracker: https://github.com/yourusername/iranian_banks/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/banks.json
    - assets/images/
topics:
  - iran
  - banking
  - card
  - iban
  - flutter